spring:
  mail:
    host: smtp.163.com
    username: xxx@163.com
    password: xxx
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
               
mail:
  fromMail:
    addr: xxx@163.com
      